trigger:
- none

pool:
  vmImage: 'vs2017-win2016'
stages:
- stage: DC
  jobs:
  - job:  
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'specific'
        project: '<YOUR_PROJECT_ID>'
        pipeline: '<YOUR_PIPELINE_NO>'
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        artifactName: 'Source'
        downloadPath: '$(System.ArtifactsDirectory)\DC'
    - task: AzurePowerShell@5
      displayName: 'Azure PowerShell script: InlineScript'
      inputs:
        azureSubscription: '<SUBSCRIPTION_NAME>(<SUBSCRIPTIONID>)'
        ScriptType: InlineScript
        Inline: |
         $context = (Get-AzStorageAccount -ResourceGroupName 'storage-rg' -AccountName '<YOUR_STORAGEACCOUNT_NAME>').context
         $myToken= New-AzStorageAccountSASToken -Context $context -Service Blob -ResourceType Service,Container,Object -Permission "racwdlup" 

         Write-Host "##vso[task.setvariable variable=SASToken;]$myToken"
        azurePowerShellVersion: LatestVersion
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '<SUBSCRIPTION_NAME>(<SUBSCRIPTIONID>)'
        subscriptionId: '<SUBSCRIPTIONID>'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'SQLAlwaysOnLab'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.ArtifactsDirectory)/DC/Source/azuredeploy.json'
        csmParametersFile: '$(System.ArtifactsDirectory)/DC/Source/azuredeploy.parameters.json'
        overrideParameters: '-VMName "<YOUR_VM_NAME>" -DomainName "<YOURDOMAINNAME.net>" -_artifactsLocationSasToken "$(SASToken)"'
        deploymentMode: 'Incremental'
- stage: Workstation
  dependsOn: DC
  jobs:
   - job:
     steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'specific'
          project: '<YOUR_PROJECT_ID>'
          pipeline: '<YOUR_PIPELINE_NO>'
          buildVersionToDownload: 'latest'
          downloadType: 'single'
          artifactName: 'Source'
          downloadPath: '$(System.ArtifactsDirectory)\Workstation'
      - task: AzurePowerShell@5
        displayName: 'Azure PowerShell script: InlineScript'
        inputs:
          azureSubscription: '<SUBSCRIPTION_NAME>(<SUBSCRIPTIONID>)'
          ScriptType: InlineScript
          Inline: |
           $context = (Get-AzStorageAccount -ResourceGroupName 'storage-rg' -AccountName '<YOUR_STORAGEACCOUNT_NAME>').context
           $myToken= New-AzStorageAccountSASToken -Context $context -Service Blob -ResourceType Service,Container,Object -Permission "racwdlup" 

           Write-Host "##vso[task.setvariable variable=SASToken;]$myToken"
          azurePowerShellVersion: LatestVersion
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: '<SUBSCRIPTION_NAME>(<SUBSCRIPTIONID>)'
          subscriptionId: '<SUBSCRIPTIONID>'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'SQLAlwaysOnLab'
          location: 'East US'
          templateLocation: 'Linked artifact'
          csmFile: '$(System.ArtifactsDirectory)/Workstation/Source/azuredeploy.json'
          csmParametersFile: '$(System.ArtifactsDirectory)/Workstation/Source/azuredeploy.parameters.json'
          overrideParameters: '-VMName "<YOUR_VM_NAME>" -DomainName "<YOURDOMAINNAME.net>" -_artifactsLocationSasToken "$(SASToken)"'
          deploymentMode: 'Incremental'
- stage: SQL
  dependsOn: DC
  jobs:
   - job:
     steps:
     - task: DownloadBuildArtifacts@0
       inputs:
         buildType: 'specific'
         project: '<YOUR_PROJECT_ID>'
         pipeline: '<YOUR_PIPELINE_NO>'
         buildVersionToDownload: 'latest'
         downloadType: 'single'
         artifactName: 'Source'
         downloadPath: '$(System.ArtifactsDirectory)\SQL'
     - task: AzurePowerShell@5
       displayName: 'Azure PowerShell script: InlineScript'
       inputs:
          azureSubscription: '<SUBSCRIPTION_NAME>(<SUBSCRIPTIONID>)'
          ScriptType: InlineScript
          Inline: |
            $context = (Get-AzStorageAccount -ResourceGroupName 'storage-rg' -AccountName '<YOUR_STORAGEACCOUNT_NAME>').context
            $myToken= New-AzStorageAccountSASToken -Context $context -Service Blob -ResourceType Service,Container,Object -Permission "racwdlup" 

            Write-Host "##vso[task.setvariable variable=SASToken;]$myToken"
          azurePowerShellVersion: LatestVersion
     - task: AzureResourceManagerTemplateDeployment@3
       inputs:
         deploymentScope: 'Resource Group'
         azureResourceManagerConnection: '<SUBSCRIPTION_NAME>(<SUBSCRIPTIONID>)'
         subscriptionId: '<SUBSCRIPTIONID>'
         action: 'Create Or Update Resource Group'
         resourceGroupName: 'SQLAlwaysOnLab'
         location: 'East US'
         templateLocation: 'Linked artifact'
         csmFile: '$(System.ArtifactsDirectory)/SQL/Source/azuredeploy.json'
         csmParametersFile: '$(System.ArtifactsDirectory)/SQL/Source/azuredeploy.parameters.json'
         overrideParameters: '-VMName "<YOUR_VM_NAME>" -DomainName "<YOURDOMAINNAME.net>" -_artifactsLocationSasToken "$(SASToken)"'
         deploymentMode: 'Incremental'